# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM python:3.12-slim
WORKDIR /app

# Install system dependencies for pillow
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       libjpeg-dev zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy project
COPY pyproject.toml .
COPY base64_server.py .
COPY base64_server ./base64_server

# Install runtime dependencies
RUN pip install --no-cache-dir mcp[cli] pillow

# Set non-root user
RUN useradd --create-home appuser
USER appuser

# Expose potential port (not used for stdio)
EXPOSE 0

# Default command
ENTRYPOINT ["python", "base64_server.py"]
